### ISSUE TITLE
The commands under "Try it out" fail

### ISSUE THREAD

**Issue by vilcans** [amethyst/atelier-assets#28]
I'm new to Atelier, so I tried to follow the "Try it out" instructions in the readme but failed:

```$ cargo run --release
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/vagrant/atelier-assets/daemon/Cargo.toml
workspace: /home/vagrant/atelier-assets/Cargo.toml
error: `cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: atelier-daemon, atelier-client, atelier-cli
```

So I tried specifying I wanted to run atelier-cli:

```
 $ cargo run --release --bin atelier-client
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/vagrant/atelier-assets/daemon/Cargo.toml
workspace: /home/vagrant/atelier-assets/Cargo.toml
    Finished release [optimized] target(s) in 0.22s
     Running `target/release/atelier-client`
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread '<unnamed>' panicked at 'failed to create named pipe: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:1084:5
```

So that's not the right way to do it either. Also tried running atelier-daemon instead:

``` $ cargo run --release --bin atelier-daemon
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/vagrant/atelier-assets/daemon/Cargo.toml
workspace: /home/vagrant/atelier-assets/Cargo.toml
   Compiling openssl-sys v0.9.48
   Compiling alsa-sys v0.1.2
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/vagrant/atelier-assets/target/release/build/alsa-sys-0f3a895d3b79df9d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

So it seems something is missing in the getting started instructions.

The above is on Ubuntu and master branch, Rust nightly (stable failed some other way I don't have the log from).

**Comment by kabergstrom** [comment]
Hi! 
Thank you for taking the time to try this out!

I am sorry I haven't maintained the instructions properly, I'll get to it as soon as I am able. In the meantime, a good way to test things out is to run the `experimental` example in my `amethyst` fork:
https://github.com/kabergstrom/amethyst/tree/new-asset-system

```
cd amethyst_assets
cargo run --example experimental --features experimental-assets
```

This demonstrates a simple loading example, and you can see an example engine integration there. Check the `mod experimental` in `lib.rs` of `amethyst_assets`.

**Comment by vilcans** [comment]
Thanks. I got it to build and run.
